sudo: required

language: node_js

services:
  - docker

script:
  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT -t $TRAVIS_REPO_SLUG:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
