// flow-typed signature: d29aa585d19036e308ba7f5ecf245ffa
// flow-typed version: <<STUB>>/igdb-api-node_v^3.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'igdb-api-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'igdb-api-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'igdb-api-node/configuration' {
  declare module.exports: any;
}

declare module 'igdb-api-node/lib/endpoints' {
  declare module.exports: any;
}

declare module 'igdb-api-node/lib/get-image' {
  declare module.exports: any;
}

declare module 'igdb-api-node/lib/index' {
  declare module.exports: any;
}

declare module 'igdb-api-node/lib/parse-endpoint' {
  declare module.exports: any;
}

declare module 'igdb-api-node/lib/perform-request' {
  declare module.exports: any;
}

declare module 'igdb-api-node/lib/request-endpoint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'igdb-api-node/configuration.js' {
  declare module.exports: $Exports<'igdb-api-node/configuration'>;
}
declare module 'igdb-api-node/lib/endpoints.js' {
  declare module.exports: $Exports<'igdb-api-node/lib/endpoints'>;
}
declare module 'igdb-api-node/lib/get-image.js' {
  declare module.exports: $Exports<'igdb-api-node/lib/get-image'>;
}
declare module 'igdb-api-node/lib/index.js' {
  declare module.exports: $Exports<'igdb-api-node/lib/index'>;
}
declare module 'igdb-api-node/lib/parse-endpoint.js' {
  declare module.exports: $Exports<'igdb-api-node/lib/parse-endpoint'>;
}
declare module 'igdb-api-node/lib/perform-request.js' {
  declare module.exports: $Exports<'igdb-api-node/lib/perform-request'>;
}
declare module 'igdb-api-node/lib/request-endpoint.js' {
  declare module.exports: $Exports<'igdb-api-node/lib/request-endpoint'>;
}
