// flow-typed signature: 340aba2322b9639902311757fe96e845
// flow-typed version: <<STUB>>/mockgoose_v^7.3.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mockgoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mockgoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mockgoose/bugs/158/app' {
  declare module.exports: any;
}

declare module 'mockgoose/bugs/158/test' {
  declare module.exports: any;
}

declare module 'mockgoose/bugs/190' {
  declare module.exports: any;
}

declare module 'mockgoose/bugs/192' {
  declare module.exports: any;
}

declare module 'mockgoose/bugs/204-2' {
  declare module.exports: any;
}

declare module 'mockgoose/bugs/204' {
  declare module.exports: any;
}

declare module 'mockgoose/bugs/63' {
  declare module.exports: any;
}

declare module 'mockgoose/built/mockgoose-helper' {
  declare module.exports: any;
}

declare module 'mockgoose/built/mockgoose' {
  declare module.exports: any;
}

declare module 'mockgoose/built/Mockgoose/src/mockgoose' {
  declare module.exports: any;
}

declare module 'mockgoose/built/mongodb-prebuilt/built/mongodb-prebuilt-all' {
  declare module.exports: any;
}

declare module 'mockgoose/specifyVersion' {
  declare module.exports: any;
}

declare module 'mockgoose/test' {
  declare module.exports: any;
}

declare module 'mockgoose/test/15' {
  declare module.exports: any;
}

declare module 'mockgoose/test/170' {
  declare module.exports: any;
}

declare module 'mockgoose/test/179' {
  declare module.exports: any;
}

declare module 'mockgoose/test/189' {
  declare module.exports: any;
}

declare module 'mockgoose/test/195' {
  declare module.exports: any;
}

declare module 'mockgoose/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mockgoose/bugs/158/app.js' {
  declare module.exports: $Exports<'mockgoose/bugs/158/app'>;
}
declare module 'mockgoose/bugs/158/test.js' {
  declare module.exports: $Exports<'mockgoose/bugs/158/test'>;
}
declare module 'mockgoose/bugs/190.js' {
  declare module.exports: $Exports<'mockgoose/bugs/190'>;
}
declare module 'mockgoose/bugs/192.js' {
  declare module.exports: $Exports<'mockgoose/bugs/192'>;
}
declare module 'mockgoose/bugs/204-2.js' {
  declare module.exports: $Exports<'mockgoose/bugs/204-2'>;
}
declare module 'mockgoose/bugs/204.js' {
  declare module.exports: $Exports<'mockgoose/bugs/204'>;
}
declare module 'mockgoose/bugs/63.js' {
  declare module.exports: $Exports<'mockgoose/bugs/63'>;
}
declare module 'mockgoose/built/mockgoose-helper.js' {
  declare module.exports: $Exports<'mockgoose/built/mockgoose-helper'>;
}
declare module 'mockgoose/built/mockgoose.js' {
  declare module.exports: $Exports<'mockgoose/built/mockgoose'>;
}
declare module 'mockgoose/built/Mockgoose/src/mockgoose.js' {
  declare module.exports: $Exports<'mockgoose/built/Mockgoose/src/mockgoose'>;
}
declare module 'mockgoose/built/mongodb-prebuilt/built/mongodb-prebuilt-all.js' {
  declare module.exports: $Exports<'mockgoose/built/mongodb-prebuilt/built/mongodb-prebuilt-all'>;
}
declare module 'mockgoose/specifyVersion.js' {
  declare module.exports: $Exports<'mockgoose/specifyVersion'>;
}
declare module 'mockgoose/test.js' {
  declare module.exports: $Exports<'mockgoose/test'>;
}
declare module 'mockgoose/test/15.js' {
  declare module.exports: $Exports<'mockgoose/test/15'>;
}
declare module 'mockgoose/test/170.js' {
  declare module.exports: $Exports<'mockgoose/test/170'>;
}
declare module 'mockgoose/test/179.js' {
  declare module.exports: $Exports<'mockgoose/test/179'>;
}
declare module 'mockgoose/test/189.js' {
  declare module.exports: $Exports<'mockgoose/test/189'>;
}
declare module 'mockgoose/test/195.js' {
  declare module.exports: $Exports<'mockgoose/test/195'>;
}
declare module 'mockgoose/test/index.js' {
  declare module.exports: $Exports<'mockgoose/test/index'>;
}
